package com.karamba121.backend.features.access;

public enum AdministrativeAuditEventType {
    OAUTH_CLIENT_CREATED,
    OAUTH_CLIENT_UPDATED,
    OAUTH_CLIENT_DELETED,
    TENANT_MEMBERSHIP_ROLE_ASSIGNED,
    TENANT_MEMBERSHIP_SUSPENDED,
    TENANT_MEMBERSHIP_REMOVED
}
