package com.karamba121.backend.features.access;

public enum SecurityAuditEventType {
    OAUTH_CLIENT_CREATED,
    OAUTH_CLIENT_UPDATED,
    OAUTH_CLIENT_DELETED,
    OAUTH_CLIENT_SECRET_ROTATED,
    TENANT_MEMBERSHIP_ROLE_ASSIGNED,
    TENANT_MEMBERSHIP_SUSPENDED,
    TENANT_MEMBERSHIP_REMOVED,
    MFA_ENROLLMENT_STARTED,
    MFA_ENABLED,
    MFA_RECOVERY_CODES_REGENERATED,
    MFA_DISABLED,
    MFA_CHALLENGE_SUCCEEDED,
    MFA_CHALLENGE_FAILED,
    PASSKEY_REGISTERED,
    PASSKEY_REMOVED,
    PASSKEY_AUTHENTICATION_SUCCEEDED,
    FEDERATED_IDENTITY_LINKED,
    FEDERATED_IDENTITY_UNLINKED,
    FEDERATED_AUTHENTICATION_SUCCEEDED,
    ADAPTIVE_STEP_UP_REQUIRED,
    ADAPTIVE_PASSWORD_AUTHENTICATION_DENIED,
    ADAPTIVE_STEP_UP_SUCCEEDED,
    SCIM_USER_CREATED,
    SCIM_USER_UPDATED,
    SCIM_USER_DELETED
}
