package com.karamba121.backend.features.access;

public enum SecurityAuditEventType {
    OAUTH_CLIENT_CREATED,
    OAUTH_CLIENT_UPDATED,
    OAUTH_CLIENT_DELETED,
    TENANT_MEMBERSHIP_ROLE_ASSIGNED,
    TENANT_MEMBERSHIP_SUSPENDED,
    TENANT_MEMBERSHIP_REMOVED,
    MFA_ENROLLMENT_STARTED,
    MFA_ENABLED,
    MFA_RECOVERY_CODES_REGENERATED,
    MFA_DISABLED,
    MFA_CHALLENGE_SUCCEEDED,
    MFA_CHALLENGE_FAILED
}
